"""empty message

Revision ID: 73036db9d0e9
Revises: 
Create Date: 2018-08-09 14:59:39.587264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73036db9d0e9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('organizations',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('company_name', sa.String(length=60), nullable=True),
    sa.Column('load_variables', sa.String(length=60), nullable=True),
    sa.Column('variables', sa.String(length=60), nullable=True),
    sa.Column('contact_info', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_company_name'), 'organizations', ['company_name'], unique=True)
    op.create_index(op.f('ix_organizations_contact_info'), 'organizations', ['contact_info'], unique=False)
    op.create_index(op.f('ix_organizations_load_variables'), 'organizations', ['load_variables'], unique=True)
    op.create_index(op.f('ix_organizations_variables'), 'organizations', ['variables'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('username', sa.String(length=60), nullable=True),
    sa.Column('first_name', sa.String(length=60), nullable=True),
    sa.Column('last_name', sa.String(length=60), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=True)
    op.create_index(op.f('ix_employees_first_name'), 'employees', ['first_name'], unique=False)
    op.create_index(op.f('ix_employees_last_name'), 'employees', ['last_name'], unique=False)
    op.create_index(op.f('ix_employees_username'), 'employees', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employees_username'), table_name='employees')
    op.drop_index(op.f('ix_employees_last_name'), table_name='employees')
    op.drop_index(op.f('ix_employees_first_name'), table_name='employees')
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.drop_table('employees')
    op.drop_table('roles')
    op.drop_index(op.f('ix_organizations_variables'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_load_variables'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_contact_info'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_company_name'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_table('departments')
    # ### end Alembic commands ###
